Automate first four affiliated cert tests
test-network-function/cnfcert-tests-verification pull request #19
Opened 2021-12-17 21:03 UTC by theemj

2021-12-20 18:28 UTC, kononovn requested changes

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/affiliatedcertparameters/paramaters.go
> +	CertifiedContainer1                  = "nodejs-12/ubi8"
Please re-name this var from CertifiedContainer1 to CertifiedContainerNodeJsUbi

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/affiliatedcertparameters/paramaters.go
> +	CertifiedContainer2                  = "openjdk-11-rhel7/openjdk"
Please rename this var

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/affiliatedcertparameters/paramaters.go
> +	UncertifiedContainer1                = "foo/bar"
Please re-name this var

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_container.go
> +		By("Add container information to tnf_config.yml")
Please remove hardcoded tnf_config.yml and use one from globalparameters.go

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_container.go
> +		By("Start tests")
Should be "Start test"

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_container.go
> +		By("Add container information to tnf_config.yml")
Please remove hardcoded tnf_config.yml and use one from globalparameters.go

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_container.go
> +		By("Start tests")
test

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_container.go
> +		Expect(err).ToNot(HaveOccurred())
Let's add more logs. Please add optionalDescritpion for every expect call.
For example: Expect(err).ToNot(HaveOccurred(), "Error to define tnf config file")

2021-12-20 18:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_container.go
> +		By("Start tests")
test

2021-12-20 18:28 UTC, kononovn commented on tests/globalhelper/helper.go
> +func defineCertifiedContainerInfo(config *globalparameters.TnfConfig, certifiedContainerInfo []string) error {
Please re-name to defineCertifiedContainersInfo

2021-12-22 15:22 UTC, kononovn commented
lgtm

2021-12-22 15:24 UTC, kononovn approved these changes
Looks good to me, well done!

2021-12-22 15:32 UTC, sebrandon1 approved these changes
One nit about a logging line but otherwise looks good!

2021-12-22 15:32 UTC, sebrandon1 commented on tests/globalhelper/helper.go
> +
Might I suggest adding a logging line here with the `name` and `repo`.

2021-12-22 16:51 UTC, sebrandon1 commented
Thanks!

2021-12-22 17:09 UTC, merged