Improve ginkgo installation script
test-network-function/cnfcert-tests-verification pull request #281
Opened 2023-03-27 11:47 UTC by bnshr

2023-03-27 21:26 UTC, theemj approved these changes
looks good and works on my test cluster :+1:

2023-03-27 21:32 UTC, sebrandon1 requested changes
Make the required version the one specified in the go.mod.

2023-03-27 21:32 UTC, sebrandon1 commented on scripts/install-ginkgo.sh
> +REQUIRED_GINKGO_VERSION="2.9.2"
Required version should get brought in from the go.mod:

`$(awk '/ginkgo/ {printf "%s/ginkgo@%s", $1, $2}' go.mod)`

2023-03-28 14:30 UTC, bnshr commented on scripts/install-ginkgo.sh
> +        go mod init tmp
Yeah, that's right.

2023-03-28 14:46 UTC, sebrandon1 approved these changes

2023-03-28 15:12 UTC, merged

2023-03-28 19:09 UTC, bnshr commented
Thanks!