Automated next 4 lifecycle tests
test-network-function/cnfcert-tests-verification pull request #30
Opened 2022-01-24 10:32 UTC by shaior

2022-01-24 22:34 UTC, theemj approved these changes
looks good to me!

2022-01-26 09:07 UTC, greyerof reviewed
Just a couple of personal recommendations/suggestions for this project:
- Helpers files: There's no need to prepend the test suite name as prefix for a helper file like "lifehelper.go"/"nethelper.go" -> it can be just "helper.go". You can have several helpers.go in your code base, as long as they belong to different packages (nethelper, lifecyclehelper...).
- Helper file's function names: There's no need to include the name of the package in the name. For instance, you can have two different "DefineDeployment" functions, defined in different packages:
   nethelper.DefineDeployment()        -> Creates a deployment with network related fields.
   lifecyclehelper.DefineDeployment()  -> Creates a deployment with lifecycle related fields (shutdown, terminationGracePeriod...).

2022-01-26 09:07 UTC, greyerof commented on tests/lifecycle/tests/lifecycle_shutdown.go
> +		"that does not have preStop field configured [negative]", func() {
"that does not have" -> "that don't have"

2022-01-26 09:07 UTC, greyerof commented on tests/utils/deployment/deployment.go
> +	deployment.Spec.Template.Spec.Containers[0].Lifecycle = &corev1.Lifecycle{
You should assert that "len(Containers) > 0" before accessing its first element.

2022-01-26 13:59 UTC, shaior commented on tests/lifecycle/tests/lifecycle_shutdown.go
> +	It("One deployment, one pod with one container that"+
Done, thank you.

2022-01-26 13:59 UTC, shaior commented on tests/lifecycle/lifehelper/lifehelper.go
> +func DefineLifecycleDeployment(moreThanOneContainer bool, deploymentName string) *v1.Deployment {
Done, thank you.

2022-01-26 14:08 UTC, shaior commented on tests/lifecycle/tests/lifecycle_shutdown.go
> +		By("Define second deployment with preStop field configured", func() {
it happen because I added func() by mistake to By, thank you!

2022-01-26 16:53 UTC, greyerof approved these changes

2022-01-26 23:07 UTC, kononovn requested changes
Looks good, just few more steps

2022-01-26 23:07 UTC, kononovn commented on tests/lifecycle/tests/lifecycle_shutdown.go
> +		replicaDefinedDeployment := globalhelper.AppendContainersToDeployment(
Basically these lines are duplicated across all tests 

```
globalhelper.AppendContainersToDeployment(
			deployment.RedefineWithReplicaNumber(
				deployment.DefineDeployment(
					"lifecycleput",
					lifeparameters.LifecycleNamespace,
					globalhelper.Configuration.General.TnfImage,
					lifeparameters.TestDeploymentLabels), 3),
			2,
			globalhelper.Configuration.General.TnfImage)

		preStopDeploymentStruct := deployment.RedefineAllContainersWithPreStopSpec(
			replicaDefinedDeployment, lifeparameters.PreStopCommand)

```
Can you move them in to a new helper function.
Something like: 
func DefineLifecycleDeploymentPreStop(preStop bool) {
...
}

2022-01-27 18:49 UTC, kononovn approved these changes
Looks good to me

2022-01-27 18:49 UTC, merged