Automated scaling test
test-network-function/cnfcert-tests-verification pull request #32
Opened 2022-01-30 15:07 UTC by shaior

2022-01-31 11:22 UTC, greyerof approved these changes

2022-02-02 03:04 UTC, kononovn commented on tests/lifecycle/tests/lifecycle_scaling.go
> +// in order to run the test, export TNF_NON_INTRUSIVE_ONLY=false.
Please set this variable automatically in your test and then remove it in After each section. Use  os.Setenv func.

2022-02-02 03:06 UTC, kononovn requested changes
Looks good. Thanks you for keeping your PRs small. Just 1 more minor change required.

2022-02-02 03:07 UTC, kononovn commented
Please add 1 more suite in README file

2022-02-02 13:00 UTC, kononovn approved these changes
Looks good to me

2022-02-02 13:00 UTC, merged