Operator cert skip cases
test-network-function/cnfcert-tests-verification pull request #53
Opened 2022-03-17 20:32 UTC by theemj

Updated case where there are no operators to be certified and removed outdated skip cases that are no longer relevant.

2022-03-20 08:26 UTC, shaior approved these changes
lgtm

2022-03-22 19:28 UTC, kononovn requested changes

2022-03-22 19:28 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_operator.go
> +		// no operators labeled to be tested, just need to run the test
Please remove this comment. The name of the test case describe the idea of this test.

2022-03-23 14:03 UTC, hamadise approved these changes

2022-03-23 18:19 UTC, merged