Uncertified operator version
test-network-function/cnfcert-tests-verification pull request #64
Opened 2022-04-14 15:44 UTC by theemj

Test cases (and supporting changes) for the scenario in which an operator does belong to the "certified-operators" group in the Red Hat catalog, but the version installed is not certified for the ocp version.

2022-04-17 06:18 UTC, shaior approved these changes
lgtm.

2022-04-19 15:50 UTC, kononovn commented on tests/affiliatedcertification/affiliatedcerthelper/operator.go
> +func DisableCatalogSource(name string) error {
This function looks the same as EnableCatalogSource.
You can create common private function setCatalogSource(enable bool, name string) and re-use this helper function from DisableCatalogSource and EnableCatalogSource

2022-04-19 15:51 UTC, kononovn commented on tests/affiliatedcertification/affiliatedcertparameters/parameters.go
> +	CertifiedOperatorPrefixKubeturbo         = "kubeturbo-operator"
Same var as CertifiedOperatorDeploymentKubeturbo

2022-04-19 15:55 UTC, kononovn commented on tests/affiliatedcertification/tests/affiliated_certification_operator.go
> +				"k10-kasten-operator",
You have this string in parameters

2022-04-19 15:57 UTC, kononovn requested changes
Please fix few minor comments above.

2022-04-20 14:23 UTC, kononovn approved these changes
Looks good

2022-04-20 16:25 UTC, merged